# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeasurementEnums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MeasurementEnums.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16MeasurementEnums.proto*\x98\x01\n\x04TYPE\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x14\n\x10VIBRATION_VECTOR\x10\x01\x12\x12\n\x0e\x43URRENT_VECTOR\x10\x02\x12\x0f\n\x0bTEMPERATURE\x10\x03\x12\x0e\n\nMACHINE_ON\x10\x04\x12\x0f\n\x0bMACHINE_OFF\x10\x05\x12\x11\n\rVIBRATION_RMS\x10\x0c\x12\x0f\n\x0b\x43URRENT_RMS\x10\r*3\n\x07\x43HANNEL\x12\x13\n\x0f\x43HANNEL_UNKNOWN\x10\x00\x12\x05\n\x01X\x10\x01\x12\x05\n\x01Y\x10\x02\x12\x05\n\x01Z\x10\x04*\x96\x01\n\x04\x46REQ\x12\x10\n\x0c\x46REQ_UNKNOWN\x10\x00\x12\t\n\x05HZ_50\x10\x01\x12\n\n\x06HZ_100\x10\x02\x12\n\n\x06HZ_200\x10\x03\x12\n\n\x06HZ_400\x10\x04\x12\n\n\x06HZ_800\x10\x05\x12\x0b\n\x07HZ_1600\x10\x06\x12\x0b\n\x07HZ_3200\x10\x07\x12\x0b\n\x07HZ_6400\x10\x08\x12\x0c\n\x08HZ_12800\x10\t\x12\x0c\n\x08HZ_25600\x10\n*S\n\x05RANGE\x12\x11\n\rRANGE_UNKNOWN\x10\x00\x12\x07\n\x03G_2\x10\x01\x12\x07\n\x03G_4\x10\x02\x12\x07\n\x03G_8\x10\x03\x12\x08\n\x04G_16\x10\x04\x12\x08\n\x04G_32\x10\x05\x12\x08\n\x04G_64\x10\x06*N\n\nERROR_TYPE\x12\x0e\n\nERROR_NONE\x10\x00\x12\x0b\n\x07NO_BUFS\x10\x01\x12\x10\n\x0cINVALID_CONF\x10\x02\x12\x11\n\rCOMMUNICATION\x10\x03*K\n\rACCELEROMETER\x12\x19\n\x15\x41\x43\x43\x45LEROMETER_UNKNOWN\x10\x00\x12\t\n\x05KX13x\x10\x01\x12\t\n\x05KX132\x10\x02\x12\t\n\x05KX124\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TYPE = _descriptor.EnumDescriptor(
  name='TYPE',
  full_name='TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIBRATION_VECTOR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURRENT_VECTOR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMPERATURE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MACHINE_ON', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MACHINE_OFF', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIBRATION_RMS', index=6, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURRENT_RMS', index=7, number=13,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=27,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

TYPE = enum_type_wrapper.EnumTypeWrapper(_TYPE)
_CHANNEL = _descriptor.EnumDescriptor(
  name='CHANNEL',
  full_name='CHANNEL',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHANNEL_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Y', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=181,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_CHANNEL)

CHANNEL = enum_type_wrapper.EnumTypeWrapper(_CHANNEL)
_FREQ = _descriptor.EnumDescriptor(
  name='FREQ',
  full_name='FREQ',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FREQ_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_50', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_100', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_200', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_400', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_800', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_1600', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_3200', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_6400', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_12800', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HZ_25600', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=235,
  serialized_end=385,
)
_sym_db.RegisterEnumDescriptor(_FREQ)

FREQ = enum_type_wrapper.EnumTypeWrapper(_FREQ)
_RANGE = _descriptor.EnumDescriptor(
  name='RANGE',
  full_name='RANGE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RANGE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_2', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_4', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_8', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_16', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_32', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G_64', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=387,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_RANGE)

RANGE = enum_type_wrapper.EnumTypeWrapper(_RANGE)
_ERROR_TYPE = _descriptor.EnumDescriptor(
  name='ERROR_TYPE',
  full_name='ERROR_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_BUFS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_CONF', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMUNICATION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=472,
  serialized_end=550,
)
_sym_db.RegisterEnumDescriptor(_ERROR_TYPE)

ERROR_TYPE = enum_type_wrapper.EnumTypeWrapper(_ERROR_TYPE)
_ACCELEROMETER = _descriptor.EnumDescriptor(
  name='ACCELEROMETER',
  full_name='ACCELEROMETER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCELEROMETER_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KX13x', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KX132', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KX124', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=552,
  serialized_end=627,
)
_sym_db.RegisterEnumDescriptor(_ACCELEROMETER)

ACCELEROMETER = enum_type_wrapper.EnumTypeWrapper(_ACCELEROMETER)
TYPE_UNKNOWN = 0
VIBRATION_VECTOR = 1
CURRENT_VECTOR = 2
TEMPERATURE = 3
MACHINE_ON = 4
MACHINE_OFF = 5
VIBRATION_RMS = 12
CURRENT_RMS = 13
CHANNEL_UNKNOWN = 0
X = 1
Y = 2
Z = 4
FREQ_UNKNOWN = 0
HZ_50 = 1
HZ_100 = 2
HZ_200 = 3
HZ_400 = 4
HZ_800 = 5
HZ_1600 = 6
HZ_3200 = 7
HZ_6400 = 8
HZ_12800 = 9
HZ_25600 = 10
RANGE_UNKNOWN = 0
G_2 = 1
G_4 = 2
G_8 = 3
G_16 = 4
G_32 = 5
G_64 = 6
ERROR_NONE = 0
NO_BUFS = 1
INVALID_CONF = 2
COMMUNICATION = 3
ACCELEROMETER_UNKNOWN = 0
KX13x = 1
KX132 = 2
KX124 = 3


DESCRIPTOR.enum_types_by_name['TYPE'] = _TYPE
DESCRIPTOR.enum_types_by_name['CHANNEL'] = _CHANNEL
DESCRIPTOR.enum_types_by_name['FREQ'] = _FREQ
DESCRIPTOR.enum_types_by_name['RANGE'] = _RANGE
DESCRIPTOR.enum_types_by_name['ERROR_TYPE'] = _ERROR_TYPE
DESCRIPTOR.enum_types_by_name['ACCELEROMETER'] = _ACCELEROMETER


# @@protoc_insertion_point(module_scope)
