# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MeasurementEnums_pb2 as MeasurementEnums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Report.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cReport.proto\x1a\x16MeasurementEnums.proto\"\xd0\x01\n\nReportItem\x12\x13\n\x04type\x18\x01 \x01(\x0e\x32\x05.TYPE\x12\x1a\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x0b.ERROR_TYPE\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x15\n\x05range\x18\x04 \x01(\x0e\x32\x06.RANGE\x12\n\n\x02\x66s\x18\x05 \x01(\r\x12\x13\n\x0bsensitivity\x18\x06 \x01(\r\x12%\n\raccelerometer\x18\x07 \x01(\x0e\x32\x0e.ACCELEROMETER\x12\x11\n\trawFormat\x18\x08 \x01(\t\x12\r\n\x05value\x18\t \x01(\x0c\"d\n\x06Report\x12\x10\n\x08\x63onfigId\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\x1a\n\x05\x65rror\x18\x03 \x01(\x0e\x32\x0b.ERROR_TYPE\x12\x19\n\x04item\x18\x04 \x03(\x0b\x32\x0b.ReportItem')
  ,
  dependencies=[MeasurementEnums__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REPORTITEM = _descriptor.Descriptor(
  name='ReportItem',
  full_name='ReportItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ReportItem.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='ReportItem.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='ReportItem.channels', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='ReportItem.range', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fs', full_name='ReportItem.fs', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensitivity', full_name='ReportItem.sensitivity', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer', full_name='ReportItem.accelerometer', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rawFormat', full_name='ReportItem.rawFormat', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ReportItem.value', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=249,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configId', full_name='Report.configId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Report.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='Report.error', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='Report.item', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=351,
)

_REPORTITEM.fields_by_name['type'].enum_type = MeasurementEnums__pb2._TYPE
_REPORTITEM.fields_by_name['error'].enum_type = MeasurementEnums__pb2._ERROR_TYPE
_REPORTITEM.fields_by_name['range'].enum_type = MeasurementEnums__pb2._RANGE
_REPORTITEM.fields_by_name['accelerometer'].enum_type = MeasurementEnums__pb2._ACCELEROMETER
_REPORT.fields_by_name['error'].enum_type = MeasurementEnums__pb2._ERROR_TYPE
_REPORT.fields_by_name['item'].message_type = _REPORTITEM
DESCRIPTOR.message_types_by_name['ReportItem'] = _REPORTITEM
DESCRIPTOR.message_types_by_name['Report'] = _REPORT

ReportItem = _reflection.GeneratedProtocolMessageType('ReportItem', (_message.Message,), dict(
  DESCRIPTOR = _REPORTITEM,
  __module__ = 'Report_pb2'
  # @@protoc_insertion_point(class_scope:ReportItem)
  ))
_sym_db.RegisterMessage(ReportItem)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), dict(
  DESCRIPTOR = _REPORT,
  __module__ = 'Report_pb2'
  # @@protoc_insertion_point(class_scope:Report)
  ))
_sym_db.RegisterMessage(Report)


# @@protoc_insertion_point(module_scope)
